on:
  push:
    branches: ["main","develop"]
  pull_request:
    branches: ["main","develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with gradlew
        run: ./graldew clean build